[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "help-me-tibooo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "beautifulsoup4==4.15.0",
  "curl_cffi==0.13.0",
  "httpx==0.28.1",
]

[project.optional-dependencies]
test = [
  "PyYAML==6.0.2",
  "pytest==9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]
